### ISSUE TITLE
qapitrace: segfault on saving framebuffer

### ISSUE THREAD

**Issue by sliedes** [apitrace/apitrace#334]
This segfaults qapitrace HEAD (8a1ba735):

1. Download CivBE.trace.lz from https://drive.google.com/file/d/0BwgPzH1WFyIuUEVLQ0NtVGlOSVU/view?usp=sharing (sorry, 233 M compressed; I intend to file a trimming bug using this file too), decompress with lzip -d
2. Run qapitrace on CivBE.trace.
3. Scroll down to frame 500
4. Select Lookup State
5. In the Current State pane, go to the Surfaces tab
6. Right-click GL_BACK and choose Save Image

Expected result: The image is saved.
Actual result: qapitrace segfaults with this backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000046687b in ApiTraceCall::index (this=0x0) at /home/sliedes/projects/apitrace/gui/apitracecall.cpp:852
852	    return m_index;
#0  0x000000000046687b in ApiTraceCall::index (this=0x0) at /home/sliedes/projects/apitrace/gui/apitracecall.cpp:852
#1  0x000000000049db01 in MainWindow::saveSelectedSurface (this=0x7fffffffd9b0) at /home/sliedes/projects/apitrace/gui/mainwindow.cpp:1517
#2  0x00000000004f680a in MainWindow::qt_static_metacall (_o=0x7fffffffd9b0, _c=QMetaObject::InvokeMetaMethod, _id=30, _a=0x7fffffffba30) at /home/sliedes/projects/apitrace/build-dbg/gui/moc_mainwindow.cpp:330
#3  0x00007ffff3a2d90d in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff76c4732 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff76c6db8 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff784439a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff7849ca4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff784e38e in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff770a148 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff784eba3 in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff76cbf3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff76d197c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff39fef1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff76d011a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7728754 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff772add3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff76cbf3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff76d1380 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff39fef1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff429d5c3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#21 0x00007ffff429ee25 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#22 0x00007ffff428455f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#23 0x00007fffe8e56f50 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#24 0x00007ffff221bc5d in g_main_dispatch (context=0x7fffe00016f0) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3111
#25 g_main_context_dispatch (context=context@entry=0x7fffe00016f0) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3710
#26 0x00007ffff221bf48 in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3781
#27 0x00007ffff221bffc in g_main_context_iteration (context=0x7fffe00016f0, may_block=1) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3842
#28 0x00007ffff3a56537 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff39fc752 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff784d280 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x0000000000499b23 in MainWindow::showSurfacesMenu (this=0x7fffffffd9b0, pos=...) at /home/sliedes/projects/apitrace/gui/mainwindow.cpp:891
#32 0x00000000004f67e8 in MainWindow::qt_static_metacall (_o=0x7fffffffd9b0, _c=QMetaObject::InvokeMetaMethod, _id=28, _a=0x7fffffffcac0) at /home/sliedes/projects/apitrace/build-dbg/gui/moc_mainwindow.cpp:328
#33 0x00007ffff3a2d90d in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff76f5ba5 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff770ae47 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff780c7fe in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff791e0bb in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff795dc40 in QTreeView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff39fed0a in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff76cbf1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff76d1d24 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff39fef1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ffff7728a5f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff772add3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff76cbf3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff76d1380 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff39fef1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007ffff429d5c3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#49 0x00007ffff429ee25 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#50 0x00007ffff428455f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#51 0x00007fffe8e56f50 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#52 0x00007ffff221bc5d in g_main_dispatch (context=0x7fffe00016f0) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3111
#53 g_main_context_dispatch (context=context@entry=0x7fffe00016f0) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3710
#54 0x00007ffff221bf48 in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3781
#55 0x00007ffff221bffc in g_main_context_iteration (context=0x7fffe00016f0, may_block=1) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3842
#56 0x00007ffff3a56537 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007ffff39fc752 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00007ffff3a041cc in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00000000004afd33 in main (argc=2, argv=0x7fffffffde18) at /home/sliedes/projects/apitrace/gui/main.cpp:97
```

**Comment by jrfonseca** [comment]
The crash is fixed.

However, note that looking up state on a call seems a bad idea -- it will dump the state of the _first_ call in the frame (not the last...)

I think you really should dump the state in the exact point you want. Or we should improve qapitrace to use the swapbuffer call, or the disallow dumping frame state completely.
