### ISSUE TITLE
gltrim segfaults if glDeleteTexture called with binding zero

### ISSUE THREAD

**Issue by phire** [apitrace/apitrace#714]
According to the OpenGL reference pages

> glDeleteTextures silently ignores 0's and names that do not correspond to existing textures.

Backtrace:

```
#0  0x0000aaaaaab2d374 in frametrim::UsedObject::id (this=0x0) at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_dependecyobject.cpp:47
#1  0x0000aaaaaab2d9a8 in frametrim::DependecyObjectMap::destroy (this=0xaaaaaac898d8, call=...)
    at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_dependecyobject.cpp:124
#2  0x0000aaaaaab75cd8 in std::__invoke_impl<void, void (frametrim::DependecyObjectMap::*&)(trace::Call const&), frametrim::TextureObjectMap*&, trace::Call const&> (__f=
    @0xaaaaaac903b0: (void (frametrim::DependecyObjectMap::*)(frametrim::DependecyObjectMap * const, const trace::Call &)) 0xaaaaaab2d8c4 <frametrim::DependecyObjectMap::destroy(trace::Call const&)>, __t=@0xaaaaaac903c0: 0xaaaaaac898d8) at /usr/include/c++/10.2.0/bits/invoke.h:73
#3  0x0000aaaaaab73e74 in std::__invoke<void (frametrim::DependecyObjectMap::*&)(trace::Call const&), frametrim::TextureObjectMap*&, trace::Call const&> (
    __fn=
    @0xaaaaaac903b0: (void (frametrim::DependecyObjectMap::*)(frametrim::DependecyObjectMap * const, const trace::Call &)) 0xaaaaaab2d8c4 <frametrim::DependecyObjectMap::destroy(trace::Call const&)>) at /usr/include/c++/10.2.0/bits/invoke.h:95
#4  0x0000aaaaaab72388 in std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>::__call<void, trace::Call const&, 0ul, 1ul>(std::tuple<trace::Call const&>&&, std::_Index_tuple<0ul, 1ul>) (this=0xaaaaaac903b0, __args=...)
    at /usr/include/c++/10.2.0/functional:416
#5  0x0000aaaaaab70cd0 in std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>::operator()<trace::Call const&, void>(trace::Call const&) (this=0xaaaaaac903b0) at /usr/include/c++/10.2.0/functional:499
#6  0x0000aaaaaab6f69c in std::__invoke_impl<void, std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>&, trace::Call const&>(std::__invoke_other, std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>&, trace::Call const&) (__f=...) at /usr/include/c++/10.2.0/bits/invoke.h:60
#7  0x0000aaaaaab6d288 in std::__invoke_r<void, std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>&, trace::Call const&>(std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)>&, trace::Call const&) (__fn=...) at /usr/include/c++/10.2.0/bits/invoke.h:110
#8  0x0000aaaaaab6ae5c in std::_Function_handler<void (trace::Call const&), std::_Bind<void (frametrim::DependecyObjectMap::*(frametrim::TextureObjectMap*, std::_Placeholder<1>))(trace::Call const&)> >::_M_invoke(std::_Any_data const&, trace::Call const&) (__functor=..., __args#0=...)
    at /usr/include/c++/10.2.0/bits/std_function.h:291
#9  0x0000aaaaaab4a53c in std::function<void (trace::Call const&)>::operator()(trace::Call const&) const (this=0xaaaaaac90388, __args#0=...)
    at /usr/include/c++/10.2.0/bits/std_function.h:622
#10 0x0000aaaaaab3fca4 in frametrim::FrameTrimmeImpl::call (this=0xaaaaaac894f0, call=..., frametype=frametrim::ft_none)
    at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_frametrimmer.cpp:246
#11 0x0000aaaaaab3f880 in frametrim::FrameTrimmer::call (this=0xfffffffff4b8, call=..., target_frame_type=frametrim::ft_none)
    at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_frametrimmer.cpp:184
#12 0x0000aaaaaab769a0 in trim_to_frame (filename=0xfffffffffd0f "/home/phire/gta3/re3.2.trace", options=...)
    at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_main.cpp:157
#13 0x0000aaaaaab77198 in main (argc=6, argv=0xfffffffffa68) at /home/phire/aur/apitrace-git/src/apitrace/frametrim/ft_main.cpp:278
```

**Comment by gerddie** [comment]
@phire Can you test #718 with your trace?
