### ISSUE TITLE
freedoom doesn't like to be traced

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#792]
with enforce x11:

```
[📦 io.github.freedoom.Phase2 apitrace]$ SDL_VIDEODRIVER=x11 ./apitrace trace -d -o freedoom-gl-high.trace gzdoom
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gzdoom...
(No debugging symbols found in gzdoom)
(gdb) r
Starting program: /app/bin/gzdoom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
apitrace: loaded into /app/bin/gzdoom
[New Thread 0x7ffff6cda640 (LWP 981)]
GZDoom g4.7.0-m - 2021-09-21 22:08:33 +0200 - SDL version
Compiled on Oct 19 2021

[Detaching after vfork from child process 982]
apitrace: loaded into /usr/bin/bash
apitrace: unloaded from /usr/bin/bash
OS: Freedesktop.org 21.08.13 (Flatpak runtime), Linux 5.17.0-1-amd64 on x86_64
M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /app/share/games/doom/gzdoom.pk3, 666 lumps
 adding /app/share/games/doom/game_support.pk3, 2514 lumps
 adding /app/share/games/doom/freedoom2.wad, 3649 lumps
 adding /app/share/games/doom/game_widescreen_gfx.pk3, 164 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Family 6, Model 140, Stepping 1
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
[New Thread 0x7ffff5d36640 (LWP 983)]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[New Thread 0x7ffff5535640 (LWP 984)]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
  Opened device Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones
[New Thread 0x7ffff4d34640 (LWP 985)]
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 98.27 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
Adding dehacked patch freedoom2.wad:DEHACKED
Patch installed
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
===========================================================================
This is Freedoom, the free content first person shooter.

Freedoom is freely redistributable under the terms of the modified BSD
license. Check out the Freedoom website for more information:

    https://freedoom.github.io/
============================================================================
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
apitrace: redirecting dlopen("libGL.so.1", 0x102) from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
apitrace: tracing to freedoom-gl-high.trace
[New Thread 0x7fffe19e8640 (LWP 986)]
[New Thread 0x7fffe11e7640 (LWP 987)]
[New Thread 0x7fffe09e6640 (LWP 988)]
[New Thread 0x7fffd3fff640 (LWP 989)]
[New Thread 0x7fffd37fe640 (LWP 990)]
[New Thread 0x7fffd2ffd640 (LWP 991)]
[New Thread 0x7fffd27fc640 (LWP 992)]
[New Thread 0x7fffd1ffb640 (LWP 993)]
apitrace: attempting to read configuration file: /home/okias/.var/app/io.github.freedoom.Phase2/config/apitrace/gltrace.conf
[Thread 0x7fffd1ffb640 (LWP 993) exited]
[New Thread 0x7fffd1ffb640 (LWP 994)]
[Thread 0x7fffd1ffb640 (LWP 994) exited]
Using video driver x11
apitrace: redirecting dlopen("libGL.so.1", 0x102) from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
[New Thread 0x7fffd1ffb640 (LWP 995)]
[Thread 0x7fffd1ffb640 (LWP 995) exited]
[New Thread 0x7fffd1ffb640 (LWP 996)]

Thread 1 "gzdoom" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d0ae77 in gltrace::_glGetIntegerv_override(unsigned int, int*) () from /home/projects/collabora/flatpak_shared/apitrace/wrappers/glxtrace.so
(gdb) bt
#0  0x00007ffff7d0ae77 in gltrace::_glGetIntegerv_override(unsigned int, int*) ()
   from /home/projects/collabora/flatpak_shared/apitrace/wrappers/glxtrace.so
#1  0x00007ffff7b88197 in glGetIntegerv ()
   from /home/projects/collabora/flatpak_shared/apitrace/wrappers/glxtrace.so
#2  0x0000555555c60d03 in gl_LoadExtensions() ()
#3  0x0000555555c63983 in OpenGLRenderer::OpenGLFrameBuffer::InitializeState() ()
#4  0x0000555555c45f32 in IVideo::SetResolution() ()
#5  0x0000555555c4611f in V_Init2() ()
#6  0x0000555555983f1d in GameMain() ()
#7  0x00005555557b45b3 in main ()
```

with wayland EGL:
```
Using video driver wayland
apitrace: redirecting dlopen("libGL.so.1", 0x2) from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
apitrace: redirecting dlopen("libEGL.so.1", 0x2) from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
apitrace: tracing to /home/projects/collabora/flatpak_shared/apitrace/gzdoom.trace
apitrace: warning: unknown function "eglQueryDevicesEXT"
apitrace: warning: unknown function "eglDupNativeFenceFDANDROID"
apitrace: attempting to read configuration file: /home/okias/.var/app/io.github.freedoom.Phase2/config/apitrace/gltrace.conf


*** Fatal Error ***
```

**Comment by jrfonseca** [comment]
I'll close this one.
